spring.application.name=pswmanager
server.port=8081

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pswmanager}
spring.datasource.username=${DB_USERNAME:user}
spring.datasource.password=${DB_PASSWORD:user}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Root logging level
logging.level.root=INFO
# Application logging level
logging.level.com.portfolio.keyra=INFO
# Spring framework logging
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO

logging.file.name=logs/pswmanager.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB

logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p --- [%t] %-40.40logger{39} : %m%n%wEx

server.servlet.session.timeout=30m

server.servlet.session.tracking-modes=cookie

# Cookie settings
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=${COOKIE_SECURE:false}
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.name=KEYRA_SESSION
spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.servlet.multipart.location=${java.io.tmpdir}

rate-limit.strict.capacity=5
rate-limit.normal.capacity=10
rate-limit.window.ms=60000

audit-log.retention-days=90

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.security.oauth2.client.registration.keyra.client-id=keyra-web
spring.security.oauth2.client.registration.keyra.client-secret=keyra-web-secret
spring.security.oauth2.client.registration.keyra.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keyra.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.keyra.scope=openid, profile
spring.security.oauth2.client.provider.keyra.issuer-uri=http://localhost:9000/keyra